# PROBLEM 2 - Even Fibonacci numbers
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibonacci(max_num):
    fib_list = [1]
    num1 = 1
    num2 = 1
    while num2 <= max_num:
        fib_list.append(num2)
        temp = num1
        num1 = num2
        num2 = temp + num1
    return fib_list

def sum_of_even(lst):
    total = 0
    for num in lst:
        if num % 2 == 0:
            total += num
    return total
            
print(sum_of_even(fibonacci(4000000)))
