# PROBLEM 12 - Highly divisible triangular number

"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

def factors(number):
    count = 0
    for i in range(1, number+1):
        if number % i == 0:
            count += 1
    return count

target = 500
counter = 0
n = 5200

while counter <= target:
    triangular_num = int((n * (n + 1)) / 2)
    counter = factors(triangular_num)
    print('current number of factors: {} for number {}'.format(counter, triangular_num))
    n += 1
    
print(triangular_num)
# left on 25000000